// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/belly-breathing-redesign/Current.tsx": () => import("../components/mockups/belly-breathing-redesign/Current.tsx"),
  "./components/mockups/belly-breathing-redesign/OrganicMotion.tsx": () => import("../components/mockups/belly-breathing-redesign/OrganicMotion.tsx"),
  "./components/mockups/belly-breathing-signature/BreathingGlyph.tsx": () => import("../components/mockups/belly-breathing-signature/BreathingGlyph.tsx"),
  "./components/mockups/belly-breathing-signature/CurrentSignature.tsx": () => import("../components/mockups/belly-breathing-signature/CurrentSignature.tsx"),
  "./components/mockups/belly-breathing-signature/LuminousVeil.tsx": () => import("../components/mockups/belly-breathing-signature/LuminousVeil.tsx"),
  "./components/mockups/belly-breathing-signature/ResonantField.tsx": () => import("../components/mockups/belly-breathing-signature/ResonantField.tsx"),
  "./components/mockups/breath-science-diaphragm/CurrentScience.tsx": () => import("../components/mockups/breath-science-diaphragm/CurrentScience.tsx"),
  "./components/mockups/breath-science-diaphragm/DiaphragmMotion.tsx": () => import("../components/mockups/breath-science-diaphragm/DiaphragmMotion.tsx")
};
