// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/belly-breathing-redesign/Current.tsx": () => import("../components/mockups/belly-breathing-redesign/Current.tsx"),
  "./components/mockups/belly-breathing-redesign/OrganicMotion.tsx": () => import("../components/mockups/belly-breathing-redesign/OrganicMotion.tsx")
};
